dist: trusty
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-littlesnitch-rules
  - AWS_DEFAULT_REGION=us-east-1
  - secure: KaVUD9px9laLHV6YXMG8wxVUyR3NfaYZS9hLtewY9dN9vqBFZdgYn+mmoQlWk3YmAIJ/qlhX4Lvu/gHAQqH4EB+RtY6pSjok85lCM3JgncxMgREpGbwjkLpf/bCIGv2xeJZ+8kMDJCKBlaXvmifieD3QBKKxM0cHtqJy8FWm06jB6Cwdq84+J+M1jH0yQkqTB9QAxggwbIp/hqLhL4Xcvx71/iKlFqqaDvYHDdLl7qbTSjzC9zK2PgEPa35OJ4lHXUb+TXEYPwcasmpkf+pQoB4oYyHwgWHam0OVAEq14anxJ4M6WVZKJ7SAZ5OFJe/TMuBDVosxE82Jt8Y+r8IB64Pg1DVUYEfNN4DOowZgoZ1rLxCu5t9Yv5TyVuEZ5LEX93ISMUGvMaZ7TeFVCRoVH71czGKYZUqEVO+IxEFvw6g7TAr1dfoTnZ0iqiLEj0ExfoSfl64qpS9A5eMOm6+a+03fW+aEIqE+wu9tZ54X1UXQCIz2higtRBgMnaSceCa9n69w++PyKfttlYKsQ3EFXRZHqK6h/F41//+AXZourFHavlgTqL5aYkQpMEmdIWEF7h+Vdy4nPtzISx+/YwN3A8P8jjYA4SOBtz5iW4JK/gW+JE5QHSFiQH91qy1aBGYnr17RiHzTzxrO8mhCslxRXhLlkKzaC32pFBml26e/TyA=
  - secure: MFre92IwYvq+uEaQtz+mwMVAchbcYx72WyX+0mUm4hcoiClsPY1IQhhzjIfoOSQFf/PI6p8kb/0ZjOJ5xEEagPpZYyQNjSZR1tnjN9HRxPUTXwQOT8nt83RQ8rgUsoN2yfGo/xHU8JVt6i5QFW8g8ZaJH/kpzp9vetzkbGk8t9Ha4WjdGPWnxYKwNeocIWy0XshpGnMJCCSoxehcCxI+MmqIEriZOIZJtldek0dY6DzJWKhC7dlklSe1ypu3x/n5Zgwd3qYhc2VzZwxhTpmSk1xk2ZicQ9qCRPLH9JGLnPXoS1Na7dcWtaoAGef8V/4+D9bbrmz8Co3I7A2SxF1M/oXPnL0fY6Rbjvxphmu9KJQmkz5cyG9m5WkbkjogjVpOkGqSj+Dh+3TxuMTOR8prA7L3BTn8+QwUoToc1rc5mWGmLLr5bjxNFOPkIoTHMHsAMw5pEvq/nbo70LCHI/HU5QDVaaIfAJQblMmE85MqVXHu4gP4Se/JMmXkJghfXFZLV8/ZipoLcXXeixA+srXM94eADiCf6a+tvrPbg2LeV2KK9uI6YCzsnoZ2kTL45e+zHRG8xqiBUFFKHpwgu4gf+FTkS6IaaYsYWE2RVORg3y5l0jhAObrnrCg3IxFXaT9A1sk8j0Ka4Iivdolq5IkqAH2/7Sf352EyK72yoqHYyn0=
before_install:
- pip install --user awscli
install:
- rvm install $(cat .circle-ruby)
- rvm-exec $(cat .circle-ruby) gem install bundler
- rvm-exec $(cat .circle-ruby) bundle install
script: rvm-exec $(cat .circle-ruby) bundle exec rake
deploy:
  provider: script
  script: aws s3 sync --delete _build/ s3://$BUCKET/ || travis_terminate 1
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: LYRXDxmwu/Ziiw/VH+RVh7ZChAK9yL+gMfvICIPdXx1Sy20qK28EskW1r+XDO8Fh0c0bsf5/esqPHz/ZPiRSpGHxbY9iaTb+3pxTZ2jFXQB8peC8FT1TzNsROqqLmHRYSIXT06lhZo2Ux83wekBclwHISH6QPUODcXeSizBSYdQ0Gi4/dm3o0TsrYQKhLPjKL0R0FS76sL2dQuTHaAlj4DND4aD+zRReVATgCK3kJN986DLu3HnaKoIRzMR1wjqvx25IAZRU0XP911GirK+7Yn4pmjNYtOlHYLBDsnHHcCVTWE6jZuMgg7qQNia/FIVv/c93h6FdcPea/31ts/tMEGFXU0Bg8bFG88ddKww1raSIv2+2IwZwbPa04i9qODEEiJZxo7mmCTVqTkel7Qv12WFHW55TnmvNZ9/rgVMb5y/eHz0kTPZ6945s2tDcp6EcussV6wh4qxHYNLYrE2hZVaFsINc2VKNmSUlNL0XvlovLsos0r1Bb2W0q0VZY6Gn8wIpo5Nbr8Y1Lm2HmPRXqd8FOopatcq9PDgJDhlgrzS9LB1Exvac+l14vAP55oHcgG/l10FKj7ZcnxlJrt1z8iwxu9uOmpHK4HFaL7HbAo+U/i2ShR6S3anO516FEE/i1abIA7YITR4qcXAiR1ll4IKcZTakZCfC8HvhyHheTu1I=
