dist: xenial
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - BUCKET=akerl-littlesnitch-rules
  - AWS_DEFAULT_REGION=us-east-1
  - secure: YXWNrQHV3wshTkRb5wQGBKzX4mI1tQlR4X3ntHetxPe5EtIKW0u8yvJvjpZ6gl9Wd3hNAlKVc8Tgu307MSW/G03JIYPwGGL5YNFxnF8FXyvMS5C6yWsoofgN5QlrKdc+hm6WbCvrhc3N4H7HZxjfnXqncmy4YCyd7D31A1swjfRrBoq1N5e9zyatgZHHYJTD68TtiFTdsHf28hXGS/wiKDMPGuV5DqdLggDX4WzavUP+vYu5daXhk39QyeEr+uy05nh9OYTcZjCKXuMv7BQZFzco76/AOpnSz5+K8QN9KC2ewi+V5UZPhLqw32xrkYflU+lF4+bRIPvJJHsfCgYIYAg3BykdBtS+NOFJDOf++BdxGGM6H98n70BDQ+lVzvIbnnHeQFKHdUg9XqFdY86CWxBGYM9uO6x1cnlxgnjLdczGcgUmM+fLW32U+6+KzDE5DEMEXZtZxfDC6AS7epgH9IOt/ZmLZnUTzkmCgdeZbrF3576W+6I12HZ8K7XpY9iyUgQu5BJCsAY5fUw2S6jr4fJp/b5hM9bAneYFzekCae6WG+JErIO/+EEVBIKymSTmxNxZ7I/2fvgtZDsoZJDRZnGTo543jgpnbnNVgOouSGCkMLMQu46H76ilX2KsrkBi68WlhE0l4KKKQ71VLfj+0G9d4W3BFXhSbNC7uXFJDwo=
  - secure: Lu6Vur88wUDlwWOlbGry4KcqmFO9efZ5nnuqeGk1T4KJOBhRLxdQZWQKnlR9xcWxXb+3PbJ19xEmYLqpKGqKLX/E7ZMPig8a782QQLbpogZom0Bn3fZ3W0qbOZiB0p6GPmvioQQGzw29OK5x+uwaUyTqdfVfAzeV1sh6F5/ni7W2K7w1jBOmDwNGY0h7zZsibbjfPR8Nbmkdjr2wJDc5epa2wfWYtv7AdOWMWOrV3I6LzeTDa2J4CPd868WWi3o78gA+EgFKEn2nY+XExa9UTFw5xdiSRSVG2eGvqao9oFCqgFLwZOI3Stv0jZ1C6HtCUzZU2e8U5H2VKJC/WdEMvRMs8l8+oW8Eyv4u1VZwsl/Ho64jI/37sx5HnqC4sEYue41q2OmA2j7PikwxMlBxaUDCeAdGamIfyX/Ez8/jQKWxYHpl8+mEF/msRgirL41zhVYHif0Bq2tLTe/4wnR5JejFSr5JNJxBrjjIaQM7ml1PdvdeMgrgqSQEDuGqMuEfcvruyhC9tGSEIP5Cud1W673UTzh5zSozXa+4vVuLe45zy9DSH6DSEp7cZHdAWDPfdSCq4ulmHGfqn9LJWPP9ezaHCbvxSvQvAIzJb2Ox/q0YDaa/FyOHJdooDFvk6cHlXcj5MqKe00AjaLyd6U8QhjYdEOIbGeT0As+5kQC62W0=
before_install:
- pip install --user awscli
install:
- rvm install $(cat .circle-ruby)
- rvm-exec $(cat .circle-ruby) gem install bundler
- rvm-exec $(cat .circle-ruby) bundle install
script: rvm-exec $(cat .circle-ruby) bundle exec rake
deploy:
  provider: script
  script: aws s3 sync --delete _build/ s3://$BUCKET/
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: LYRXDxmwu/Ziiw/VH+RVh7ZChAK9yL+gMfvICIPdXx1Sy20qK28EskW1r+XDO8Fh0c0bsf5/esqPHz/ZPiRSpGHxbY9iaTb+3pxTZ2jFXQB8peC8FT1TzNsROqqLmHRYSIXT06lhZo2Ux83wekBclwHISH6QPUODcXeSizBSYdQ0Gi4/dm3o0TsrYQKhLPjKL0R0FS76sL2dQuTHaAlj4DND4aD+zRReVATgCK3kJN986DLu3HnaKoIRzMR1wjqvx25IAZRU0XP911GirK+7Yn4pmjNYtOlHYLBDsnHHcCVTWE6jZuMgg7qQNia/FIVv/c93h6FdcPea/31ts/tMEGFXU0Bg8bFG88ddKww1raSIv2+2IwZwbPa04i9qODEEiJZxo7mmCTVqTkel7Qv12WFHW55TnmvNZ9/rgVMb5y/eHz0kTPZ6945s2tDcp6EcussV6wh4qxHYNLYrE2hZVaFsINc2VKNmSUlNL0XvlovLsos0r1Bb2W0q0VZY6Gn8wIpo5Nbr8Y1Lm2HmPRXqd8FOopatcq9PDgJDhlgrzS9LB1Exvac+l14vAP55oHcgG/l10FKj7ZcnxlJrt1z8iwxu9uOmpHK4HFaL7HbAo+U/i2ShR6S3anO516FEE/i1abIA7YITR4qcXAiR1ll4IKcZTakZCfC8HvhyHheTu1I=
